# Generated by Django 5.0.6 on 2024-05-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMapNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('map_pin_id', models.IntegerField()),
                ('date_published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
