# Generated by Django 5.0.6 on 2024-05-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0002_rename_usermapnotes_usermapnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermapnote',
            name='is_visible',
        ),
    ]
