# Generated by Django 5.0.6 on 2024-05-10 11:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0003_remove_usermapnote_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPinCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_pin_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('map_pins', models.ManyToManyField(to='mnotes.mappincoordinate')),
            ],
        ),
    ]
