# Generated by Django 5.0.6 on 2024-05-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mnotes", "0003_alter_usermapnote_map_pin_point"),
    ]

    operations = [
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="WorldBorder",
        ),
    ]
