# Generated by Django 5.0.6 on 2024-05-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0004_mappincoordinate_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermapnote',
            options={'ordering': ['-date_published'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='mnotes/avt.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usermapnote',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='usermapnote',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='usermapnote',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Title'),
        ),
    ]
