# Generated by Django 5.0.6 on 2024-05-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0006_alter_user_map_pins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='C:\\projects\\web-django\\mapawish\\mnotes/avt.jpg', upload_to=''),
        ),
    ]
